# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec: macOS ``.app`` bundle of AudioVisualizer.

Parallel to ``AudioVisualizer.spec`` (Windows ``.exe``); never used on Windows.
Bundles PortAudio (via ``sounddevice``) for the mic/BlackHole path and the pyobjc
ScreenCaptureKit frameworks for the native system-audio tap. Build with
``tools/mac/build-app.sh``.
"""

import os
import sys

from PyInstaller.utils.hooks import (
    collect_data_files,
    collect_dynamic_libs,
    collect_submodules,
)

sys.path.insert(0, os.path.abspath("src"))

from audio_visualizer.config import APP_NAME, APP_VERSION_MAC  # noqa: E402

# PortAudio dylib shipped with sounddevice (the mic / BlackHole capture path).
binaries = collect_dynamic_libs("sounddevice")

# Packaged assets (logo/icon PNGs) so the resource loader finds them under
# sys._MEIPASS in the frozen build.
_assets_src = os.path.abspath(os.path.join("src", "audio_visualizer", "assets"))
datas = (
    [(_assets_src, os.path.join("audio_visualizer", "assets"))]
    if os.path.isdir(_assets_src)
    else []
)
datas += collect_data_files("sounddevice")

# Visual modes load dynamically (registry.discover), and the ScreenCaptureKit tap
# imports pyobjc frameworks lazily — collect both so the frozen app finds them.
hiddenimports = [
    *collect_submodules("audio_visualizer.visuals"),
    "sounddevice",
    "objc",
    "Foundation",
    "CoreMedia",
    "CoreAudio",
    "Quartz",
    "AVFoundation",
    "ScreenCaptureKit",
]

# .icns is generated by build-app.sh from the packaged PNG when possible.
_icon = os.path.abspath(os.path.join("build", "mac", "AudioVisualizer.icns"))
icon_arg = _icon if os.path.exists(_icon) else None

# CFBundle versions must be numeric; derive from the hex PP.FF.BB (A0 -> 160).
_num_version = ".".join(str(int(p, 16)) for p in APP_VERSION_MAC.split("."))

a = Analysis(
    ["src/audio_visualizer/__main__.py"],
    pathex=["src"],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["pyaudiowpatch"],  # Windows-only; never bundle on macOS
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,  # let macOS pass file/open args through to argv
    icon=icon_arg,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)

app = BUNDLE(
    coll,
    name=f"{APP_NAME}.app",
    icon=icon_arg,
    bundle_identifier="com.pn1619.audiovisualizer",
    version=_num_version,
    info_plist={
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleShortVersionString": _num_version,
        "CFBundleVersion": _num_version,
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "13.0",
        # Mic prompt (BlackHole / input capture path). Screen Recording (native
        # system-audio tap) is a system-managed TCC prompt and needs no key.
        "NSMicrophoneUsageDescription": (
            "AudioVisualizer visualizes audio from your selected input device."
        ),
    },
)
